Add plybooks for EAP 7.2 and include JCLIFF
redhat-cop/ansible-middleware-playbooks pull request #4
Opened 2020-07-31 15:03 UTC by hcherukuri

2020-08-05 19:58 UTC, sabre1041 requested changes
Seeing the following errors:

1. On first run:

```
TASK [jcliff] ******************************************************************************************************************************************************************************************
Wednesday 05 August 2020  14:51:32 -0500 (0:00:01.618)       0:25:25.311 ****** 
fatal: [10.9.51.52]: FAILED! => {"changed": false, "msg": "wfly_home is invalid: /opt/jboss-as/jboss-eap-7.2/ "}
```

2.  Errors on subsequent runs

```
TASK [redhat-cop.jboss_eap : Async Download JBoss EAP Patch from Red Hat Customer Portal] **************************************************************************************************************
Wednesday 05 August 2020  14:58:13 -0500 (0:00:00.432)       0:05:18.308 ****** 
fatal: [10.9.51.52]: FAILED! => {"msg": "The conditional check 'transfer_method == 'csp-to-host' and jboss_eap_apply_patch | bool and (not jboss_eap_exists.stat.exists | bool or 'base' in patch_info_result.stdout)' failed. The error was: error while evaluating conditional (transfer_method == 'csp-to-host' and jboss_eap_apply_patch | bool and (not jboss_eap_exists.stat.exists | bool or 'base' in patch_info_result.stdout)): Unable to look up a name or access an attribute in template string ({% if transfer_method == 'csp-to-host' and jboss_eap_apply_patch | bool and (not jboss_eap_exists.stat.exists | bool or 'base' in patch_info_result.stdout) %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'AnsibleUndefined' is not iterable\n\nThe error appears to be in '/Users/ablock/Projects/RHC/internal/cop/git/ansible-middleware/redhat-cop.jboss_eap/tasks/apply_patch.yml': line 43, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Async Download JBoss EAP Patch from Red Hat Customer Portal\n  ^ here\n"}
```

2020-08-06 12:50 UTC, hcherukuri commented
The problem is the first two role here are redhat-cop.jboss_common and redhat-cop.jboss_eap are two different projects and I am getting errors with Ansible 2.9. If they execute well then we have jboss-eap-7.2 on the VM then we can run the jcliff role. I don't see any where we are configuring JBOSS_HOME in any of those roles. So I have checked where it is been held and passed jboss_home for jcliff.

I tried jcliff code it works without any issues, I will work on trouble shooting the first two roles.

2020-08-06 17:59 UTC, hcherukuri commented
As mentioned to you on chat, https://github.com/redhat-cop/jboss_eap/blob/master/defaults/main.yml includes config of 7.1 so files generated will be under /opt/jboss-as/jboss-eap-7.1/, so we are seeing jboss_home issue.

2020-08-07 04:06 UTC, sabre1041 commented
@hcherukuri No longer receiving the first error as described above. Am still facing the second error

2020-08-07 11:49 UTC, hcherukuri commented
I don't see that error while running, could you let me know the command and parameters you are passing for running the 7.2 playbook. Looks to me as syntax issue. Could you apply these changes and try, https://github.com/redhat-cop/jboss_eap/pull/65.

and on which build are you running the playbook on ?

2020-08-11 00:24 UTC, sabre1041 requested changes
Everything else checks out. Please just update the collection name/version and we can merge it in!

2020-08-11 00:24 UTC, sabre1041 commented on requirements.yml
> +collections:
Can we align this with the new `wildfly.jcliff` collection? This is updated location

2020-08-11 00:24 UTC, sabre1041 commented on eap7.2-rhel7.yml
> +    - redhat.jcliff
Update to wildfly.jcliff

2020-08-11 02:31 UTC, hcherukuri commented on eap7.2-rhel7.yml
> +    - redhat.jcliff
Updated, please

2020-08-11 02:32 UTC, hcherukuri commented
Updated wildfly.jcliff in the requirments.yml and playbooks. Please proceed.

2020-08-11 02:38 UTC, sabre1041 requested changes

2020-08-11 02:38 UTC, sabre1041 commented on requirements.yml
> +    verison: 0.0.1
0.0.2 is the version we need to use

2020-08-11 03:16 UTC, sabre1041 approved these changes
LGTM

2020-08-11 03:16 UTC, merged